### ISSUE TITLE
Webpack or Rollup transpilation error - TypeError: Right-hand side of 'instanceof' is not an object

### ISSUE THREAD

**Issue by btakita** [fgnass/domino#146]
It looks like the name of the function attached to `ctor` param is stripped & given `ctor` instead.

The result is the error `TypeError: Right-hand side of 'instanceof' is not an object`

```js
import { elements } from 'domino/lib/htmlelts'
console.debug(elements) // { ctor: [Function: ctor] }
```

**Comment by btakita** [comment]
Looks like somebody else had the same issue. https://stackoverflow.com/questions/56903846/angular-universal-with-domino-getting-right-hand-side-of-instanceof-is-not-a

**Comment by dmmax** [comment]
I got same issue..

**Comment by nidi3** [comment]
Me too, see #151

**Comment by nidi3** [comment]
As the project seems to be sleeping at the moment, I published a build with this fix on npm https://www.npmjs.com/package/domino-ext.
But I would like to see it applied here on the original.

**Comment by blakeoxx** [comment]
This still appears to be an issue in release 2.1.6. The domino-ext fork works for me

**Comment by mohit-singh-pepper** [comment]
Seriously no resolution for this yet ? The projects using this like `turndown` are also not possible to bundle. Due to this.

**Comment by ElectricCodeGuy** [comment]
Now it is 2024... and still no fix??? what
